# Generated by Django 3.2.6 on 2022-06-02 05:03

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='logo',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='users',
            name='logo_thumb',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=200)),
                ('already_used', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reset_password',
            },
        ),
    ]
