# Generated by Django 3.2.6 on 2022-06-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_auto_20220602_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_expired_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email_verification_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
