# Generated by Django 3.2.6 on 2022-06-03 09:24

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_auto_20220603_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='logo_thumb',
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar_thumb',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg'])]),
        ),
    ]
