name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS EC2
      run: |
          mkdir -p ~/.ssh
          echo -e "" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh ubuntu@ "cd projects/Advista-project  && git pull origin develop && pm2 restart advista && pm2 save"


